CREATE TABLE IF NOT EXISTS address_books (
    guid TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    owner_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    is_personal BOOLEAN NOT NULL DEFAULT FALSE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ab_shares (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ab_guid TEXT NOT NULL REFERENCES address_books(guid) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    group_id INTEGER REFERENCES groups(id) ON DELETE CASCADE,
    rule INTEGER NOT NULL DEFAULT 0,
    CHECK (user_id IS NOT NULL OR group_id IS NOT NULL)
);
