CREATE TABLE IF NOT EXISTS tags (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ab_guid TEXT NOT NULL REFERENCES address_books(guid) ON DELETE CASCADE,
    name TEXT NOT NULL,
    color INTEGER NOT NULL DEFAULT 4278190080,
    UNIQUE(ab_guid, name)
);

CREATE TABLE IF NOT EXISTS peer_tags (
    peer_id INTEGER NOT NULL REFERENCES peers(id) ON DELETE CASCADE,
    tag_id INTEGER NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (peer_id, tag_id)
);
